function function_442(x)
    % Define 9 affine maps: A_all(:,:,k) * x + b_all(:,k)
    A_all = cat(3, ...
        eye(2), ...
        [0 -1; 1 0], ...
        [-1 0; 0 -1], ...
        [0 1; -1 0], ...
        [-1 0; 0 -1], ...
        [-1 0; 0 -1], ...
        [0 -1; 1 0], ...
        [-1 0; 0 -1], ...
        [0 1; -1 0] ...
    );

    b_all = [ ...
        [0; 0], ...
        [0; 0], ...
        [0; 0], ...
        [0; 0], ...
        [2; 0], ...
        [0; 2], ...
        [2; 0], ...
        [2; 2], ...
        [0; 2] ...
    ];

    figure; hold on; axis equal;
    colors = lines(9);
    
    for k = 1:9
        A = A_all(:,:,k);
        b = b_all(:,k);
        y = A * x + b;
        plot(y(1), y(2), 'o', 'Color', colors(k,:), 'MarkerSize', 10, 'LineWidth', 1.5);
        text(y(1), y(2), sprintf(' %d', k), 'Color', colors(k,:), 'FontSize', 12);
    end

    plot(x(1), x(2), 'kx', 'MarkerSize', 12, 'LineWidth', 2); % original point
    title('Affine Orbit of Input Point');
    legend('Transformed points');
    xlabel('x'); ylabel('y');
    grid on;
end